name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CONTAINER: darkrsw/2026-ds-exercise1:latest

jobs:
  test:

    runs-on: ubuntu-latest
    container:
      image: $CONTAINER
      credentials:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_PAT  }}

    steps:
    - uses: actions/checkout@v4
    - name: copy files.
      run: cp /app/ctest.cpp ./
    - name: compile
      run: g++ -o ctest.o ctest.cpp
    - name: run with time
      run: /usr/bin/time -v ./ctest.o
    
